// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRole = "commander" | "strategic_reviewer" | "tactical_evaluator" | "worker" | "skill_scout";
