// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AgentRole } from "./AgentRole";
import type { EvidenceDelta } from "./EvidenceDelta";
import type { GraphChange } from "./GraphChange";
import type { TaskGraphSnapshot } from "./TaskGraphSnapshot";
import type { TokenUsage } from "./TokenUsage";
import type { Verdict } from "./Verdict";
import type { JsonValue } from "./serde_json/JsonValue";

export type Event = { "type": "task_submitted", id: string, description: string, } | { "type": "graph_built", snapshot: TaskGraphSnapshot, } | { "type": "graph_modified", change: GraphChange, } | { "type": "agent_spawned", id: AgentId, role: AgentRole, tier: number, node_id: string | null, } | { "type": "agent_completed", id: AgentId, output_summary: string, } | { "type": "agent_cancelled", id: AgentId, partial: string | null, } | { "type": "llm_request_started", agent_id: AgentId, model: string, } | { "type": "llm_delta", agent_id: AgentId, text: string, } | { "type": "llm_response_completed", agent_id: AgentId, usage: TokenUsage, } | { "type": "tool_started", agent_id: AgentId, tool: string, args: JsonValue, } | { "type": "tool_completed", agent_id: AgentId, tool: string, result: string, success: boolean, } | { "type": "evaluation", node_id: string, status: Verdict, feedback: string, evidence_delta: EvidenceDelta | null, } | { "type": "strategic_insight", insight: string, } | { "type": "tier_escalation", node_id: string, from: number, to: number, } | { "type": "phase_changed", phase: string, } | { "type": "error", source: string, message: string, };
