// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvidenceDelta = { new_items: number, fixed_issues: number, remaining_issues: number, };
