// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InviteCode = { code: string, created_at: bigint, used_at: bigint | null, used_by_email: string | null, note: string | null, };
