// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RunDetail = { id: string, description: string, status: string, started_at: bigint, completed_at: bigint | null, result: string | null, error: string | null, events: Array<JsonValue>, has_tex: boolean, has_pdf: boolean, };
