// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RunSummary = { id: string, description: string, status: string, started_at: bigint, completed_at: bigint | null, };
